package com.pwr.internetowypomocnik.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "body_status")
public class Body_status {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_body_status;

    private Integer weight;
    private Integer height;
    private Integer biceps;
    private Integer waist;
    private Integer chest;
    private Integer leg;
    private float body_fat;



    // Public methods

    public Body_status() { }

    public Body_status(long id) {
        this.id_body_status = id;
    }

    public Body_status(Integer weight, Integer height, Integer biceps, Integer waist, Integer chest, Integer leg, float body_fat) {
        this.weight = weight;
        this.height = height;
        this.biceps = biceps;
        this.waist = waist;
        this.chest = chest;
        this.leg = leg;
        this.body_fat = body_fat;
    }

    public long getId_body_status() {
        return id_body_status;
    }

    public void setId_body_status(long id_body_status) {
        this.id_body_status = id_body_status;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getheight() {
        return height;
    }

    public void setheight(Integer height) {
        this.height = height;
    }

    public Integer getBiceps() {
        return biceps;
    }

    public void setBiceps(Integer biceps) {
        this.biceps = biceps;
    }

    public Integer getWaist() {
        return waist;
    }

    public void setWaist(Integer waist) {
        this.waist = waist;
    }

    public Integer getChest() {
        return chest;
    }

    public void setChest(Integer chest) {
        this.chest = chest;
    }

    public Integer getLeg() {
        return leg;
    }

    public void setLeg(Integer leg) {
        this.leg = leg;
    }

    public float getBody_fat() {
        return body_fat;
    }

    public void setBody_fat(float body_fat) {
        this.body_fat = body_fat;
    }

}
