package com.pwr.internetowypomocnik.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "diet")
public class Diet {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_diet;

   private Integer total_calories;
    private Integer carbohydrates;
    private Integer proteins;
    private Integer fat;
    private Integer fluid;


    // Public methods


    public Diet(Integer total_calories, Integer carbohydrates, Integer proteins, Integer fat, Integer fluid) {
        this.total_calories = total_calories;
        this.carbohydrates = carbohydrates;
        this.proteins = proteins;
        this.fat = fat;
        this.fluid = fluid;
    }

    public Diet(long id) {
        this.id_diet = id;
    }

    public long getId_diet() {
        return id_diet;
    }

    public void setId_diet(long id_diet) {
        this.id_diet = id_diet;
    }

    public Integer getTotal_calories() {
        return total_calories;
    }

    public void setTotal_calories(Integer total_calories) {
        this.total_calories = total_calories;
    }

    public Integer getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(Integer carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public Integer getFat() {
        return fat;
    }

    public void setFat(Integer fat) {
        this.fat = fat;
    }

    public Integer getFluid() {
        return fluid;
    }

    public void setFluid(Integer fluid) {
        this.fluid = fluid;
    }

    public Integer getProteins() {
        return proteins;
    }

    public void setProteins(Integer proteins) {
        this.proteins = proteins;
    }
}
