package com.pwr.internetowypomocnik.model;

import javax.persistence.*;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "exercise")
public class Exercise {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_exercise;

    private String name;
    private String muscle_group;
    private String description;
    private String difficulty;


    // Public methods


    public Exercise(String name, String muscle_group, String description, String difficulty) {
        this.name = name;
        this.muscle_group = muscle_group;
        this.description = description;
        this.difficulty = difficulty;
    }

    public Exercise(long id) {
        this.id_exercise = id;
    }

    public long getId_exercise() {
        return id_exercise;
    }

    public void setId_exercise(long id_exercise) {
        this.id_exercise = id_exercise;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMuscle_group() {
        return muscle_group;
    }

    public void setMuscle_group(String muscle_group) {
        this.muscle_group = muscle_group;
    }

    public String getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(String difficulty) {
        this.difficulty = difficulty;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
