package com.pwr.internetowypomocnik.model;

import javax.persistence.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "meal")
public class Meal {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_meal;


    @Temporal(TemporalType.DATE)
    private Date date;
   // private String date;


    private Integer user_id;


    // Public methods


    public Meal(Date date, Integer user_id) {
        this.date = date;
        this.user_id = user_id;
    }

    public Meal(String stringDate, Integer user_id) throws ParseException {

        //string_date = "10102010";
        DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        Date date = formatter.parse(stringDate);

        this.date = date;
        this.user_id = user_id;


    }

    public Meal(long id) {
        this.id_meal = id;
    }

    public long getId_meal() {
        return id_meal;
    }

    public void setId_meal(long id_meal) {
        this.id_meal = id_meal;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }


    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}
