package com.pwr.internetowypomocnik.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "meal_products")
public class Meal_products {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_meal_products;

    private Integer product_id;
    private Integer meal_id;


    // Public methods


    public Meal_products(Integer product_id, Integer meal_id) {
        this.product_id = product_id;
        this.meal_id = meal_id;
    }

    public Meal_products() {
    }

    public Meal_products(long id) {
        this.id_meal_products = id;
    }

    public long getId_meal_products() {
        return id_meal_products;
    }

    public void setId_meal_products(long id_meal_products) {
        this.id_meal_products = id_meal_products;
    }

    public Integer getProduct_id() {
        return product_id;
    }

    public void setProduct_id(Integer product_id) {
        this.product_id = product_id;
    }

    public Integer getMeal_id() {
        return meal_id;
    }

    public void setMeal_id(Integer meal_id) {
        this.meal_id = meal_id;
    }
}
