package com.pwr.internetowypomocnik.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "product")
public class Product {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_product;

    @NotNull
    private String name;


    private int carbohydrates;


    private int proteins;


    private int fat;

    private Integer user_id;



    // Public methods

    public Product() { }

    public Product(long id) {
        this.id_product = id;
    }

    public Product(String name, int carbohydrates, int proteins, int fat, Integer user_id) {
        this.name = name;
        this.carbohydrates = carbohydrates;
        this.proteins = proteins;
        this.fat = fat;
        this.user_id = user_id;
    }

    public long getId_product() {
        return id_product;
    }

    public void setId_product(long id_product) {
        this.id_product = id_product;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(int carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public int getProteins() {
        return proteins;
    }

    public void setProteins(int proteins) {
        this.proteins = proteins;
    }

    public int getFat() {
        return fat;
    }

    public void setFat(int fat) {
        this.fat = fat;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}
