package com.pwr.internetowypomocnik.model;

import javax.persistence.*;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "record")
public class Record {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_record;

    private Integer user_id;
    private Integer exercise_id;
    private float maximum;


    // Public methods


    public Record(Integer user_id, Integer exercise_id, float maximum) {
        this.user_id = user_id;
        this.exercise_id = exercise_id;
        this.maximum = maximum;
    }

    public Record() {
    }

    public Record(long id) {
        this.id_record = id;
    }

    public long getId_record() {
        return id_record;
    }

    public void setId_record(long id_record) {
        this.id_record = id_record;
    }

    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Integer getExercise_id() {
        return exercise_id;
    }

    public void setExercise_id(Integer exercise_id) {
        this.exercise_id = exercise_id;
    }

    public float getMaximum() {
        return maximum;
    }

    public void setMaximum(float maximum) {
        this.maximum = maximum;
    }
}
