package com.pwr.internetowypomocnik.model;

import javax.persistence.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by Piotr on 2016-04-22.
 */
@Entity
@Table(name = "training")
public class Training {
    // An autogenerated id (unique for each id in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id_training;


    @Temporal(TemporalType.DATE)
    private Date date;
    // private String date;


    private Integer user_id;


    // Public methods


    public Training(Date date, Integer user_id) {
        this.date = date;
        this.user_id = user_id;
    }

    public Training(String stringDate, Integer user_id) throws ParseException {

        //string_date = "10102010";
        DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        Date date = formatter.parse(stringDate);

        this.date = date;
        this.user_id = user_id;


    }

    public Training(long id) {
        this.id_training = id;
    }

    public long getId_training() {
        return id_training;
    }

    public void setId_training(long id_training) {
        this.id_training = id_training;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }


    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }
}
